Repository ckeditor/ckeditor5-table, pull requests merged in 2019-08, with the labels that each got.

#196 T/ckeditor5/1151: Adjusted `InsertTableView` for better compatibility with right–to–left (RTL) languages
  src/ui/inserttableview.js
  tests/ui/inserttableview.js
Labels: status:review+, type:sub-pr

#201 Add `aria-label` for table toolbar
  lang/contexts.json
  src/tabletoolbar.js
  tests/tabletoolbar.js
Labels: type:sub-pr

#202 Improvements for integration with track changes
  src/commands/setheadercolumncommand.js
  src/commands/setheaderrowcommand.js
  src/converters/downcast.js
  src/tableutils.js
  src/tablewalker.js
  tests/commands/setheadercolumncommand.js
  tests/commands/setheaderrowcommand.js
  tests/tablewalker.js
Labels: status:review+
